### ISSUE TITLE
Issues with MagTag walkthrough

### ISSUE THREAD

**Issue by lastcoolnameleft** [adafruit/Adafruit_Learning_System_Guides#1379]
Arduino board: MagTag (via Adabox 017)

Arduino IDE version (found in Arduino -> About Arduino menu):  N/A

List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): 
* Follow the instructions here: https://learn.adafruit.com/magtag-progress-displays/weblate-translated-percent
* Use the Circuit Python library `adafruit-circuitpython-bundle-6.x-mpy-20201221`
* On boot, receive the following error:
```
Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
Traceback (most recent call last):
  File "code.py", line 21, in <module>
  File "adafruit_magtag/magtag.py", line 84, in __init__
  File "adafruit_magtag/graphics.py", line 57, in __init__
AttributeError: 'EPaperDisplay' object cannot assign attribute 'rotation'
```

**Comment by lastcoolnameleft** [comment]
Closing.  I re-installed the bootloader and it appears to be working fine now.
