### ISSUE TITLE
PyPortal Hurricane Tracker code getting MemoryError

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_Learning_System_Guides#1778]
Using 6.3.0 version of CP and grabbing code/assets from guide:
https://learn.adafruit.com/pyportal-hurricane-tracker/hurricane-tracker
via Project Bundle:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "hurricane_tracker.py", line 164, in <module>
  File "hurricane_tracker.py", line 72, in update_display
  File "hurricane_tracker.py", line 70, in update_display
  File "adafruit_pyportal/__init__.py", line 354, in fetch
  File "adafruit_portalbase/__init__.py", line 406, in _fill_text_labels
  File "adafruit_portalbase/__init__.py", line 357, in _fetch_set_text
  File "adafruit_portalbase/__init__.py", line 252, in set_text
  File "adafruit_display_text/bitmap_label.py", line 100, in __init__
  File "adafruit_display_text/bitmap_label.py", line 177, in _reset_text
MemoryError: memory allocation failed, allocating 106064 bytes
>>> 
```

**Comment by caternuson** [comment]
Hopefully fixed with #1779
